- name: Print out the host name
  hosts: all
  tasks:
    - name: On windows hosts, make sure the telnet client is installed
      win_feature:
        name: telnet-client
      when: ansible_os_family == 'Windows'
      register: telnet_client

    - name: Print some stuff
      debug:
        msg: "Telnet client was installed"
      when: telnet_client.changed

    - name: Print some other stuff
      debug:
        msg: "Telnet client was already present"
      when: telnet_client.changed == False
